import type { AssistantAuthority, AssistantIntent } from "./types";

const AUTHORITY_BY_INTENT: Record<AssistantIntent, AssistantAuthority[]> = {
  PRODUCT_INFORMATION: ["PRODUCT_DATABASE", "KNOWLEDGE_RAG"],
  PRICE_INFORMATION: ["PRODUCT_DATABASE"],
  KIT_COMPOSITION: ["PRODUCT_DATABASE"],
  KIT_SCHEDULE: ["PRODUCT_DATABASE"],
  INGREDIENT_INFORMATION: ["PRODUCT_DATABASE", "KNOWLEDGE_RAG"],
  KIT_COMPARISON: ["PRODUCT_DATABASE", "KNOWLEDGE_RAG"],
  PLAN_EXPLANATION: ["DOCTOR_APPROVED_PLAN", "CLINICAL_RULE_ENGINE"],
  SEQUENCE_EXPLANATION: ["DOCTOR_APPROVED_PLAN", "CLINICAL_RULE_ENGINE"],
  SUPPRESSED_KIT_EXPLANATION: ["CLINICAL_RULE_ENGINE"],
  SAFETY_OR_ADVERSE_EVENT: ["PRODUCT_DATABASE"],
  GENERAL_HAIR_EDUCATION: ["KNOWLEDGE_RAG"],
  SYSTEM_TRANSPARENCY: ["PRODUCT_DATABASE", "KNOWLEDGE_RAG"],
};

export function authoritiesForIntent(intent: AssistantIntent): AssistantAuthority[] {
  return [...AUTHORITY_BY_INTENT[intent]];
}
