import type { GeneralKnowledgeEntry, HairKnowledgeTopic, KnowledgeContentType, KnowledgeTaxonomyDomain } from "./knowledgeTypes";
import { findCatalogueKit } from "./fullCatalogue";
import { getKitIngredientFacts, PRODUCT_FORMULATION_CATALOGUE } from "./productFormulations";

const REVIEWED_AT = "2026-08-05";
const REVIEWED_BY = "Dr. FACT governed five-kit RAG audit";
const SOURCE_VERSION = "five-kit-controlled-v1";

type EntryInput = {
  id: string;
  title: string;
  topic: HairKnowledgeTopic;
  taxonomyDomain: KnowledgeTaxonomyDomain;
  canonicalEntity: string;
  aliases: string[];
  contentType: KnowledgeContentType;
  productFamily?: string;
  variant?: string;
  sourceDocument: string;
  sourceSection: string;
  content: string;
  keywords: string[];
  authorityScore?: number;
  missingInformation?: string[];
  conflictingInformation?: string[];
  ingredient?: string;
  role?: string;
  pathway?: string;
  kitSpecificRationale?: string;
  sourceVersion?: string;
  sourceUrl?: string;
};

function entry(input: EntryInput): GeneralKnowledgeEntry {
  return {
    id: input.id,
    title: input.title,
    domain: "HAIR",
    topic: input.topic,
    knowledgeSystem: input.topic === "LIFESTYLE" ? "NUTRITION_LIFESTYLE" : "TRICHOLOGY",
    language: "en",
    content: input.content,
    keywords: input.keywords,
    approvalStatus: "PUBLISHED_PATIENT",
    authorityScore: input.authorityScore ?? 92,
    sourceType: "CLINICAL_PROTOCOL",
    sourceStatus: "ACTIVE",
    sourceLabel: `${input.sourceDocument} / ${input.sourceSection}`,
    sourceUrl: input.sourceUrl ?? "repo:src/packages/assistant-core/fiveKitKnowledge.ts",
    sourceVersion: input.sourceVersion ?? SOURCE_VERSION,
    effectiveFrom: REVIEWED_AT,
    metadata: {
      taxonomyDomain: input.taxonomyDomain,
      canonicalEntity: input.canonicalEntity,
      aliases: input.aliases,
      audience: ["DOCTOR", "PATIENT"],
      contentType: input.contentType,
      productFamily: input.productFamily,
      variant: input.variant,
      sourceDocument: input.sourceDocument,
      sourceSection: input.sourceSection,
      reviewedBy: REVIEWED_BY,
      reviewedAt: REVIEWED_AT,
      missingInformation: input.missingInformation,
      conflictingInformation: input.conflictingInformation,
      ingredient: input.ingredient,
      role: input.role,
      pathway: input.pathway,
      kitSpecificRationale: input.kitSpecificRationale,
    },
    claims: [{
      claimId: `${input.id}_CLAIM_1`,
      claimType: input.contentType === "SAFETY_NOTE" ? "SAFETY_WORDING" : input.taxonomyDomain === "KIT" || input.taxonomyDomain === "KIT_VARIANT" ? "MEDICAL_MECHANISM" : "GENERAL_EDUCATION",
      statement: input.content,
      evidenceStatus: "SUPPORTED",
      approvalStatus: "PUBLISHED_PATIENT",
      audience: "PATIENT",
      effectiveFrom: REVIEWED_AT,
    }],
  };
}

const phenotypeKit = findCatalogueKit("Inflammation Phenotype");
const phenotypeIngredientFacts = phenotypeKit ? getKitIngredientFacts(phenotypeKit) : undefined;
const rationaleIngredientNames = new Set(["n acetyl cysteine", "nac", "curcumin", "resveratrol", "vitamin d"]);
const normalizeIngredient = (value: string) => value.toLowerCase().replace(/[^a-z0-9]+/g, " ").trim();
const missingRationaleIngredients = [...new Map((phenotypeIngredientFacts?.products.flatMap((product) => product.ingredients) ?? [])
  .filter((row) => !rationaleIngredientNames.has(normalizeIngredient(row.ingredientName)))
  .map((row) => [normalizeIngredient(row.ingredientName), row])).values()];

export const FIVE_KIT_CONTROLLED_KNOWLEDGE: GeneralKnowledgeEntry[] = [
  entry({
    id: "FIVEKIT_TE_GOLD_OVERVIEW_V1",
    title: "TE Gold overview and mechanism",
    topic: "HAIR_CONDITION",
    taxonomyDomain: "KIT",
    canonicalEntity: "KIT_TE_GOLD",
    aliases: ["TE Gold", "Hair Fact TE Gold", "TE kit"],
    contentType: "DOCTOR_EXPLANATION",
    productFamily: "TE Gold",
    sourceDocument: "Clinical Chunks sheet",
    sourceSection: "TE GOLD indication/objective/strategy",
    content: "TE GOLD is the five-kit pilot family used for telogen-effluvium-type active shedding patterns. Its treatment objective is to interrupt active shedding and support normal follicular cycling by addressing internal imbalance signals such as nutritional depletion, inflammatory load, metabolic stress and stress regulation. Exact ingredients and strengths must come from the structured formulation records, not this narrative record.",
    keywords: ["te gold", "telogen effluvium", "active shedding", "hair shedding", "mechanism", "objective"],
  }),
  entry({
    id: "FIVEKIT_GI_GOLD_OVERVIEW_V1",
    title: "GI Gold overview and mechanism",
    topic: "HAIR_BIOLOGY",
    taxonomyDomain: "KIT",
    canonicalEntity: "KIT_GI_HEALTH_GOLD",
    aliases: ["GI Gold", "GI Health Gold", "Pro Fact GI Health Gold"],
    contentType: "DOCTOR_EXPLANATION",
    productFamily: "GI Gold",
    sourceDocument: "Clinical Chunks sheet",
    sourceSection: "GI GOLD indication/objective/strategy",
    content: "GI GOLD is the five-kit pilot family for gut-imbalance signals that may affect hair through nutrient absorption, microbiome balance, inflammation regulation and gut-brain stress pathways. It should not be triggered by minor bloating or constipation alone unless the deterministic rule set supports that selection. Exact ingredients and strengths must come from structured formulation records.",
    keywords: ["gi gold", "gut health", "microbiome", "dysbiosis", "hair", "mechanism"],
  }),
  entry({
    id: "FIVEKIT_PRO_IMMUNE_GOLD_OVERVIEW_V1",
    title: "Pro Immune Gold overview and mechanism",
    topic: "HAIR_BIOLOGY",
    taxonomyDomain: "KIT",
    canonicalEntity: "KIT_PRO_IMMUNE_GOLD",
    aliases: ["Pro Immune", "Pro Immune Gold", "Proimmune Gold"],
    contentType: "DOCTOR_EXPLANATION",
    productFamily: "Pro Immune Gold",
    sourceDocument: "Clinical Chunks sheet",
    sourceSection: "PRO IMMUNE GOLD indication/objective/strategy",
    content: "PRO IMMUNE GOLD is the five-kit pilot family for immune-balance and recovery-support signals. The documented objective is to support immune balance, systemic inflammation regulation, oxidative-stress reduction, sleep or stress support and gut-skin optimisation. It must be described as supportive education and not as a replacement for medical therapy.",
    keywords: ["pro immune gold", "proimmune", "immune", "recovery", "inflammation", "oxidative stress"],
  }),
  entry({
    id: "FIVEKIT_INFLAMMATION_PHENOTYPE_OVERVIEW_V1",
    title: "Inflammation Phenotype overview and mechanism",
    topic: "SCALP_CONDITION",
    taxonomyDomain: "KIT",
    canonicalEntity: "KIT_INFLAMMATION_PHENOTYPE",
    aliases: ["Inflammation Phenotype", "Phenotype Inflammation", "Pro Fact Inflammation Phenotype", "inflammation kit"],
    contentType: "DOCTOR_EXPLANATION",
    productFamily: "Inflammation Phenotype",
    sourceDocument: "Clinical Chunks sheet",
    sourceSection: "PHENOTYPE INFLAMMATION indication/objective/strategy",
    content: "Inflammation Phenotype is the five-kit pilot family for chronic low-grade inflammatory signals that may contribute to persistent shedding, weak follicles and poor cycle recovery. Its documented pathways include inflammatory cytokine control, immune modulation, oxidative protection, androgen-sensitivity support and stress regulation. The prior source prose lists nine named items while the pilot kit-product sheet lists eight kit products; exact ingredient answers must use the structured formulation workbook and show discrepancies rather than silently reconciling them.",
    keywords: ["inflammation phenotype", "phenotype inflammation", "inflammation", "oxidative stress", "curcumin", "nac", "mechanism"],
    conflictingInformation: ["Pilot knowledge prose and kit-product rows use different counting levels for Inflammation Phenotype."],
  }),
  entry({
    id: "FIVEKIT_INFLAMMATION_PATHWAYS_V1",
    title: "Inflammation Phenotype therapeutic pathways",
    topic: "HAIR_BIOLOGY",
    taxonomyDomain: "KIT",
    canonicalEntity: "KIT_INFLAMMATION_PHENOTYPE",
    aliases: ["Inflammation Phenotype pathways", "this phenotype pathways"],
    contentType: "THERAPEUTIC_PATHWAY",
    productFamily: "Inflammation Phenotype",
    sourceDocument: "Clinical Chunks sheet",
    sourceSection: "PHENOTYPE INFLAMMATION strategy",
    content: "The approved Inflammation Phenotype strategy targets five documented support pathways: inflammatory cytokine control, immune modulation, oxidative protection, androgen-sensitivity support and stress regulation. These are formulation objectives, not proof that the kit treats a disease or is selected for an individual patient.",
    keywords: ["inflammation phenotype", "pathways", "cytokines", "immune modulation", "oxidative protection", "androgen sensitivity", "stress regulation"],
  }),
  entry({
    id: "FIVEKIT_INFLAMMATION_CLINICAL_RELEVANCE_V1",
    title: "Inflammation Phenotype clinical relevance assessment",
    topic: "SCALP_CONDITION",
    taxonomyDomain: "KIT",
    canonicalEntity: "KIT_INFLAMMATION_PHENOTYPE",
    aliases: ["Inflammation Phenotype clinical factors", "inflammatory phenotype assessment"],
    contentType: "PATIENT_FACTOR",
    productFamily: "Inflammation Phenotype",
    sourceDocument: "Clinical Chunks sheet",
    sourceSection: "PHENOTYPE INFLAMMATION indication and clinical note",
    content: "Clinical relevance assessment should look for persistent shedding or poor cycle recovery alongside chronic low-grade inflammatory signals, scalp irritation or inflammation, oxidative-stress burden, immune-related context and stress load. Severe inflammation can be prioritised over hormonal drivers only when the governed deterministic rules confirm it; these factors alone do not select the kit.",
    keywords: ["clinical factors", "assess", "persistent shedding", "scalp irritation", "inflammation", "oxidative stress", "immune", "stress"],
  }),
  entry({
    id: "FIVEKIT_INFLAMMATION_FORMULATION_RATIONALE_V1",
    title: "Inflammation Phenotype formulation rationale",
    topic: "INGREDIENT",
    taxonomyDomain: "KIT",
    canonicalEntity: "KIT_INFLAMMATION_PHENOTYPE",
    aliases: ["Inflammation Phenotype rationale", "complete formulation rationale"],
    contentType: "FORMULATION_RATIONALE",
    productFamily: "Inflammation Phenotype",
    sourceDocument: "Clinical Chunks sheet",
    sourceSection: "PHENOTYPE INFLAMMATION formulation rationale",
    content: "The approved formulation rationale groups Curcumin, NAC, Resveratrol and Vitamin D with immune modulators, androgen-sensitivity modulators, antioxidants and stress regulators to support inflammatory control, immune balance, oxidative protection, androgen-sensitivity support and stress regulation. The source does not assign a complete individual mechanism to every verified formulation row, so unrecorded ingredient rationales must not be invented.",
    keywords: ["formulation rationale", "curcumin", "nac", "resveratrol", "vitamin d", "immune modulators", "antioxidants"],
    missingInformation: ["The approved narrative does not provide an individual rationale for every structured formulation row."],
  }),
  ...[
    ["NAC", "N-acetyl cysteine", "oxidative protection"],
    ["CURCUMIN", "Curcumin", "inflammatory control and oxidative protection"],
    ["RESVERATROL", "Resveratrol", "oxidative protection"],
    ["VITAMIN_D", "Vitamin D", "immune modulation"],
  ].map(([ingredient, display, pathway]) => entry({
    id: `FIVEKIT_INFLAMMATION_INGREDIENT_${ingredient}_V1`,
    title: `${display} rationale in Inflammation Phenotype`,
    topic: "INGREDIENT",
    taxonomyDomain: "INGREDIENT",
    canonicalEntity: "KIT_INFLAMMATION_PHENOTYPE",
    aliases: [display, ingredient, `${display} in Inflammation Phenotype`],
    contentType: "INGREDIENT_ROLE",
    productFamily: "Inflammation Phenotype",
    ingredient,
    role: "Named component in the approved formulation-rationale group",
    pathway,
    kitSpecificRationale: `${display} is included in the approved Inflammation Phenotype rationale as part of the group supporting ${pathway}.`,
    sourceDocument: "Clinical Chunks sheet",
    sourceSection: "PHENOTYPE INFLAMMATION formulation rationale",
    content: `${display} is named in the approved Inflammation Phenotype formulation rationale as part of the ingredient group supporting ${pathway}. The approved source does not provide a more specific standalone mechanism or patient-selection rule for ${display}, so none should be inferred.`,
    keywords: [display.toLowerCase(), ingredient.toLowerCase(), "inflammation phenotype", "ingredient rationale", pathway],
  })),
  ...missingRationaleIngredients.map((row) => entry({
    id: `FIVEKIT_INFLAMMATION_INGREDIENT_UNDOCUMENTED_${normalizeIngredient(row.ingredientName).replaceAll(" ", "_").toUpperCase()}_V1`,
    title: `${row.ingredientName} rationale status in Inflammation Phenotype`,
    topic: "INGREDIENT",
    taxonomyDomain: "INGREDIENT",
    canonicalEntity: "KIT_INFLAMMATION_PHENOTYPE",
    aliases: [row.ingredientName, `${row.ingredientName} in Inflammation Phenotype`],
    contentType: "INGREDIENT_LIST",
    productFamily: "Inflammation Phenotype",
    ingredient: normalizeIngredient(row.ingredientName).replaceAll(" ", "_").toUpperCase(),
    role: "NOT_DOCUMENTED",
    pathway: "NOT_DOCUMENTED",
    kitSpecificRationale: "NOT_DOCUMENTED",
    sourceDocument: PRODUCT_FORMULATION_CATALOGUE.source.file,
    sourceSection: `${row.sourceSheet} row ${row.sourceRow}`,
    sourceVersion: `structured-formulation-v${PRODUCT_FORMULATION_CATALOGUE.schemaVersion}`,
    sourceUrl: `repo:${PRODUCT_FORMULATION_CATALOGUE.source.repoPath}`,
    content: `${row.ingredientName} is a verified structured formulation row for an Inflammation Phenotype component. No approved kit-specific role, pathway or rationale is documented for this ingredient, so the assistant must not invent one.`,
    keywords: [row.ingredientName.toLowerCase(), "inflammation phenotype", "rationale not documented"],
    missingInformation: ["Approved kit-specific role, pathway and rationale are not documented."],
  })),
  entry({
    id: "FIVEKIT_INFLAMMATION_SMOKING_RELEVANCE_V1",
    title: "Smoking relevance to Inflammation Phenotype assessment",
    topic: "LIFESTYLE",
    taxonomyDomain: "KIT",
    canonicalEntity: "KIT_INFLAMMATION_PHENOTYPE",
    aliases: ["smoking and Inflammation Phenotype", "smoker phenotype relevance"],
    contentType: "LIFESTYLE_IMPACT",
    productFamily: "Inflammation Phenotype",
    sourceDocument: "Controlled lifestyle-factor knowledge update",
    sourceSection: "Smoking relevance to Inflammation Phenotype",
    content: "For an active Inflammation Phenotype discussion, heavy smoking is relevant as an assessment factor because approved smoking knowledge describes added oxidative stress, vascular stress and inflammatory burden, which overlap with the phenotype's documented inflammatory and oxidative-protection context. Smoking does not automatically select this kit; only an approved deterministic rule or clinician decision can do that.",
    keywords: ["smoking", "inflammation phenotype", "oxidative stress", "inflammatory burden", "assessment", "not kit selection"],
  }),
  entry({
    id: "FIVEKIT_META_B_OVERVIEW_V1",
    title: "Meta-B overview and family identity",
    topic: "HAIR_BIOLOGY",
    taxonomyDomain: "KIT",
    canonicalEntity: "KIT_PRO_FACT_META_B",
    aliases: ["Meta B", "Meta-B", "MetaB", "Profact Meta B", "Pro Fact Meta B"],
    contentType: "OVERVIEW",
    productFamily: "Meta-B",
    sourceDocument: "Canonical Meta B identity decision",
    sourceSection: "Base kit and aliases",
    content: "PRO FACT META B is the official standalone base kit in the Meta-B family. Meta B, Meta-B, MetaB, Profact Meta B and Pro Fact Meta B are aliases of the base kit. Generic Meta-B questions resolve to the base kit only, not to IR 5, PCOS, Thyroid, Menopause or any other variant. Variant selection must come from the deterministic clinical engine or an approved patient plan.",
    keywords: ["meta b", "metab", "meta-b", "pro fact meta b", "base kit", "variant"],
  }),
  entry({
    id: "FIVEKIT_META_B_VARIANTS_V1",
    title: "Meta-B variants",
    topic: "HAIR_BIOLOGY",
    taxonomyDomain: "KIT_VARIANT",
    canonicalEntity: "KIT_PRO_FACT_META_B",
    aliases: ["Meta B variants", "Meta-B variants", "Meta B IR 5", "Meta-B IR 5", "Meta B PCOS", "Meta B Thyroid", "Meta B Menopause"],
    contentType: "VARIANT",
    productFamily: "Meta-B",
    sourceDocument: "Canonical Meta B identity decision",
    sourceSection: "Variant registry",
    content: "The currently governed Meta-B family includes the base PRO FACT META B plus registered variants PRO FACT META B PCOS, PRO FACT META B THYROID and PRO FACT META B MENOPAUSE. Meta-B IR 5 is treated as a Meta-B-family variant identity for explanation and disambiguation, but this repository does not currently contain an active structured composition record for Meta-B IR 5. Do not inherit composition, prices, claims or eligibility between the base kit and any variant unless a governed shared record explicitly authorises it.",
    keywords: ["meta b variants", "meta b ir 5", "ir 5", "pcos", "thyroid", "menopause", "variant"],
    missingInformation: ["Active structured composition record for Meta-B IR 5 is not present in the current catalogue extraction."],
  }),
  entry({
    id: "FIVEKIT_META_B_IR5_V1",
    title: "Meta-B IR 5 variant identity",
    topic: "HAIR_BIOLOGY",
    taxonomyDomain: "KIT_VARIANT",
    canonicalEntity: "KIT_PRO_FACT_META_B_IR5",
    aliases: ["Meta B IR 5", "Meta-B IR 5", "MetaB IR5", "Pro Fact Meta B IR 5"],
    contentType: "VARIANT",
    productFamily: "Meta-B",
    variant: "IR 5",
    sourceDocument: "Canonical Meta B identity decision",
    sourceSection: "Meta-B IR 5 variant identity",
    content: "Meta-B IR 5 is handled as a Meta-B-family variant identity for explanation and disambiguation. The current structured catalogue extraction does not contain an active approved composition record for Meta-B IR 5, so exact ingredients, prices, eligibility rules and patient-specific use must not be inherited from PRO FACT META B or any other Meta-B variant.",
    keywords: ["meta b ir 5", "meta-b ir 5", "metab ir5", "ir 5", "variant"],
    missingInformation: ["Active structured composition record for Meta-B IR 5 is not present in the current catalogue extraction."],
  }),  entry({
    id: "FIVEKIT_SMOKING_HAIR_V1",
    title: "Smoking and hair assessment",
    topic: "LIFESTYLE",
    taxonomyDomain: "LIFESTYLE_FACTOR",
    canonicalEntity: "SMOKING_AND_HAIR",
    aliases: ["smoking", "smoker", "tobacco", "vaping"],
    contentType: "LIFESTYLE_IMPACT",
    sourceDocument: "Controlled lifestyle-factor knowledge update",
    sourceSection: "Smoking and hair",
    content: "Smoking or heavy tobacco exposure can be relevant to hair assessment because it may add oxidative stress, vascular stress and inflammatory burden. The doctor should assess exposure level, duration, recent increase, scalp inflammation, shedding timeline, nutrition, stress, sleep and other medical causes. Smoking alone should not automatically trigger a final kit unless a governed deterministic rule supports that selection.",
    keywords: ["smoking", "smoker", "tobacco", "vaping", "hair", "oxidative stress", "assess"],
  }),
  entry({
    id: "FIVEKIT_ALCOHOL_HAIR_V1",
    title: "Alcohol and hair assessment",
    topic: "LIFESTYLE",
    taxonomyDomain: "LIFESTYLE_FACTOR",
    canonicalEntity: "ALCOHOL_AND_HAIR",
    aliases: ["alcohol", "drinking", "heavy alcohol"],
    contentType: "LIFESTYLE_IMPACT",
    sourceDocument: "Controlled lifestyle-factor knowledge update",
    sourceSection: "Alcohol and hair",
    content: "Heavy or frequent alcohol intake can be relevant to hair fall assessment through sleep disruption, nutritional compromise, inflammation, oxidative stress and liver-metabolic strain. The doctor should assess quantity, frequency, recent changes, diet quality, weight change, sleep, stress, shedding onset and lab risks such as iron or thyroid issues. Alcohol alone should not automatically map to a kit without deterministic-rule authority.",
    keywords: ["alcohol", "drinking", "hair fall", "sleep", "nutrition", "oxidative stress", "liver"],
  }),
  entry({
    id: "FIVEKIT_STRESS_HAIR_V1",
    title: "Stress and hair shedding",
    topic: "LIFESTYLE",
    taxonomyDomain: "LIFESTYLE_FACTOR",
    canonicalEntity: "STRESS_AND_HAIR",
    aliases: ["stress", "emotional stress", "physiological stress"],
    contentType: "LIFESTYLE_IMPACT",
    sourceDocument: "Controlled lifestyle-factor knowledge update",
    sourceSection: "Stress and hair",
    content: "Sustained emotional or physiological stress can be relevant to telogen-effluvium-type shedding, often with a delayed timing pattern after the trigger. The doctor should assess onset timing, illness, childbirth, surgery, sleep, diet, weight change, medicines, scalp symptoms and whether shedding is diffuse or patterned. Stress can support pathway assessment but should not by itself select a final kit in free-form RAG.",
    keywords: ["stress", "telogen effluvium", "shedding", "sleep", "hair fall", "assess"],
  }),
  entry({
    id: "FIVEKIT_SLEEP_HAIR_V1",
    title: "Poor sleep and hair assessment",
    topic: "LIFESTYLE",
    taxonomyDomain: "LIFESTYLE_FACTOR",
    canonicalEntity: "SLEEP_AND_HAIR",
    aliases: ["poor sleep", "sleep deprivation", "night shift"],
    contentType: "LIFESTYLE_IMPACT",
    sourceDocument: "Controlled lifestyle-factor knowledge update",
    sourceSection: "Poor sleep and hair",
    content: "Poor sleep or disrupted sleep timing can be relevant to hair assessment through stress-axis activation, recovery impairment, appetite or metabolic changes and inflammation burden. The doctor should assess sleep duration, night shifts, insomnia, fatigue, stress, diet, weight change and shedding timeline. Poor sleep alone should not automatically trigger a kit without deterministic rule support.",
    keywords: ["sleep", "poor sleep", "night shift", "hair", "stress", "recovery"],
  }),
  entry({
    id: "FIVEKIT_RESTRICTIVE_DIET_HAIR_V1",
    title: "Restrictive diet and hair assessment",
    topic: "LIFESTYLE",
    taxonomyDomain: "LIFESTYLE_FACTOR",
    canonicalEntity: "RESTRICTIVE_DIET_AND_HAIR",
    aliases: ["restrictive diet", "crash diet", "low protein", "dieting"],
    contentType: "LIFESTYLE_IMPACT",
    sourceDocument: "Controlled lifestyle-factor knowledge update",
    sourceSection: "Restrictive diet and hair",
    content: "Restrictive diet patterns can contribute to shedding risk when energy, protein or micronutrient intake is inadequate. The doctor should assess calorie restriction, protein intake, vegetarian or vegan pattern, iron risk, recent illness, menstrual bleeding, weight change and shedding timing. Diet history can guide assessment but should not be converted into a final kit by free-form RAG.",
    keywords: ["restrictive diet", "crash diet", "protein", "iron", "nutrition", "hair shedding"],
  }),
  entry({
    id: "FIVEKIT_RAPID_WEIGHT_LOSS_HAIR_V1",
    title: "Rapid weight loss and hair shedding",
    topic: "LIFESTYLE",
    taxonomyDomain: "LIFESTYLE_FACTOR",
    canonicalEntity: "RAPID_WEIGHT_LOSS_AND_HAIR",
    aliases: ["rapid weight loss", "weight loss", "glp1", "crash weight loss"],
    contentType: "LIFESTYLE_IMPACT",
    sourceDocument: "Controlled lifestyle-factor knowledge update",
    sourceSection: "Rapid weight loss and hair",
    content: "Rapid weight loss can be relevant to telogen-effluvium-type shedding because follicles may shift into shedding during energy deficit, illness, medication-related appetite reduction or nutrient shortfall. The doctor should assess rate of loss, dietary intake, protein, iron risk, medicines, illness and timing. Rapid weight loss alone does not authorise free-form kit selection.",
    keywords: ["rapid weight loss", "weight loss", "glp1", "telogen effluvium", "shedding", "protein"],
  }),
  entry({
    id: "FIVEKIT_TELOGEN_EFFLUVIUM_V1",
    title: "Telogen effluvium explanation",
    topic: "HAIR_CONDITION",
    taxonomyDomain: "CONDITION",
    canonicalEntity: "TELOGEN_EFFLUVIUM",
    aliases: ["telogen effluvium", "TE", "active shedding"],
    contentType: "CONDITION_EXPLANATION",
    sourceDocument: "Controlled supporting-topic knowledge update",
    sourceSection: "Telogen effluvium",
    content: "Telogen effluvium is a shedding-pattern concept in which more follicles than usual shift into the resting and shedding phase after a trigger such as illness, physiological stress, rapid weight loss, nutritional depletion, childbirth, surgery or sustained emotional stress. It is educationally distinct from progressive pattern thinning, and persistent or atypical shedding should be assessed clinically.",
    keywords: ["telogen effluvium", "te", "shedding", "stress", "weight loss", "illness"],
  }),
  entry({
    id: "FIVEKIT_GUT_HEALTH_HAIR_V1",
    title: "Gut health and hair",
    topic: "HAIR_BIOLOGY",
    taxonomyDomain: "CONDITION",
    canonicalEntity: "GUT_HEALTH_AND_HAIR",
    aliases: ["gut health", "gut imbalance", "dysbiosis", "microbiome"],
    contentType: "CONDITION_EXPLANATION",
    sourceDocument: "Controlled supporting-topic knowledge update",
    sourceSection: "Gut health and hair",
    content: "Gut-health signals can be relevant to hair assessment because digestion, microbiome balance and nutrient absorption may interact with inflammation, stress and hormonal pathways. The doctor should assess persistent digestive symptoms, diet, weight change, deficiencies, stress and whether symptoms are strong enough for deterministic pathway rules. Minor digestive symptoms alone should not select GI GOLD by free-form RAG.",
    keywords: ["gut health", "microbiome", "dysbiosis", "nutrient absorption", "gi gold", "hair"],
  }),
  entry({
    id: "FIVEKIT_IRON_THYROID_IR_SUPPORT_V1",
    title: "Iron, thyroid and insulin-resistance supporting topics",
    topic: "HAIR_CONDITION",
    taxonomyDomain: "CONDITION",
    canonicalEntity: "IRON_THYROID_INSULIN_RESISTANCE_AND_HAIR",
    aliases: ["iron deficiency", "thyroid", "insulin resistance", "IR"],
    contentType: "CONDITION_EXPLANATION",
    sourceDocument: "Controlled supporting-topic knowledge update",
    sourceSection: "Iron deficiency, thyroid and insulin resistance",
    content: "Iron deficiency, thyroid dysfunction and insulin-resistance signals can each be relevant to hair assessment, but they require appropriate history, examination and/or lab context. Free-form RAG may explain why these factors matter, but final kit selection and sequencing must come from deterministic rules or an approved patient plan.",
    keywords: ["iron deficiency", "thyroid", "insulin resistance", "metabolic", "hair", "assessment"],
  }),
];
