'use client';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { Check, Clock3, ShieldCheck, Sparkles } from 'lucide-react';
import { concernRoute, loadSkinCommonProfile, loadSkinFactIntake, nextIncompleteConcern } from '@/lib/skin-fact/skinJourney';
import styles from './anti-ageing.module.css';
export function AntiAgeingProcessing({clinicSlug,assessmentId,preview=false}:{clinicSlug:string;assessmentId:string;preview?:boolean}){
  const router=useRouter();const[stage,setStage]=useState(0);const[next,setNext]=useState<string|null>(null);
  useEffect(()=>{const timers=[setTimeout(()=>setStage(1),700),setTimeout(()=>setStage(2),1450),setTimeout(()=>setStage(3),2200)];if(!preview){const common=loadSkinCommonProfile(localStorage,clinicSlug);const intake=common?loadSkinFactIntake(localStorage,clinicSlug,common.sessionId):null;const concern=intake?nextIncompleteConcern(intake):null;setNext(concern?concernRoute(clinicSlug,concern):`/q/${clinicSlug}/skin/complete`)}return()=>timers.forEach(clearTimeout)},[clinicSlug,preview]);
  return <main className={`${styles.page} ${styles.processing}`}><section className={styles.processingCard}><div className={styles.orb}/><p className={styles.eyebrow}>Assessment received · {assessmentId.slice(0,12)}</p><h1>Your answers are ready for clinical review.</h1><p className={styles.lead}>We have securely organised your answers, documents and facial images. No diagnosis or treatment recommendation has been generated.</p><div className={styles.statusList}><span className={stage>=0?styles.active:''}>{stage>0?<Check size={15}/>:<Clock3 size={15}/>} Securing your questionnaire</span><span className={stage>=1?styles.active:''}>{stage>1?<Check size={15}/>:<ShieldCheck size={15}/>} Linking clinical image references</span><span className={stage>=2?styles.active:''}>{stage>2?<Check size={15}/>:<Sparkles size={15}/>} Preparing the factual clinician summary</span><span className={stage>=3?styles.active:''}><Check size={15}/> Pending authorised clinical review</span></div>{stage>=3&&<button className={styles.primary} onClick={()=>router.push(preview?'/design-preview/skin-fact/anti-ageing/doctor-queue':next??`/q/${clinicSlug}/skin/complete`)}>{preview?'Preview clinician queue':next?.includes('/complete')?'Finish Skin FACT journey':'Continue to next concern'}</button>}</section></main>;
}
