/**
 * masterProtocol.ts
 * Single source of truth for the DrFACT clinical questionnaire protocol.
 * Extracted from DrFACT_revamp_v44.html by the Senior Clinical Systems Architect.
 *
 * DO NOT edit this file manually. The authoritative source is:
 *   src/packages/ai-engine/questionnaire-engine/schema/questionnaire.schema.json
 *
 * This module re-exports it with full TypeScript types for use across
 * the patient-portal runtime and any future rendering clients.
 */

import rawProtocol from '../schema/questionnaire.schema.json';

// ─────────────────────────────────────────────────────────────────────────────
// SCHEMA TYPES
// ─────────────────────────────────────────────────────────────────────────────

export interface SchemaOption {
  label: string;
  value: string;
  icon: string | null;
  triggers: string[];
  clinicalTags: string[];
  followUpQuestions: string[];
  /** Option-level visibility gate (e.g. postpartum options only for Female,
   *  Norwood stages only for Male, Ludwig stages only for Female). Accepts
   *  a single rule or an array of rules combined with AND-semantics (the
   *  option is shown only when every rule matches). */
  visibleOnlyIf?:
    | { dependsOn: string; operator: string; value: string | number }
    | Array<{ dependsOn: string; operator: string; value: string | number }>;
  /** Pairwise mutual exclusion label (e.g. "Oily scalp" ↔ "Dry scalp") */
  mutuallyExclusive?: string;
  /** Photographic tile rendered above the option label (object-cover, 4:3
   *  crop). Use for real photography. */
  image?: { url: string; alt: string };
  /** Editorial diagram / SVG illustration rendered above the option label
   *  (object-contain, no crop, transparent bg). Use for schematics like the
   *  Norwood / Ludwig grade picker. */
  illustration?: { url: string; alt: string };
}

export interface SchemaSkipCondition {
  dependsOn: string;
  operator: string;
  value: string | string[];
}

export interface SchemaSkipLogicItem {
  if: SchemaSkipCondition;
  thenSkipTo: string;
  description: string;
}

export interface SchemaVisibilityRule {
  dependsOn: string;
  operator: string;
  value: string;
}

export interface SchemaDynamicFilterRule {
  description: string;
  condition: string;
  /** Only keep these options (= hide all others) when condition is true */
  filteredOptions?: string[];
  /** Remove exactly these options when condition is true */
  removedOptions?: string[];
  sourceCodeReference?: string;
}

export interface SchemaMutualExclusivityRule {
  selecting: string;
  deselects: string;
}

export interface SchemaMutualExclusivityRules {
  description: string;
  /** Optional short message shown to the user when an auto-deselection fires. */
  toastMessage?: string;
  rules: SchemaMutualExclusivityRule[];
  sourceCodeReference?: string;
}

export interface SchemaScoringSignal {
  signal: string;
  rule: string;
  sourceCodeReference?: string;
}

export interface SchemaClinicalMapping {
  condition?: string;
  value?: string;
  field?: string;
  implication?: string;
  clinicalNote?: string;
  protocol?: string;
  kits?: string[];
  usage?: string;
}

export interface SchemaValidation {
  placeholder?: string;
  min?: number;
  max?: number;
  minLength?: number;
  hint?: string;
  required?: boolean;
}

export interface SchemaUIMetadata {
  layout: string;
  voiceEnabled?: boolean;
  multiSelectConfirm?: boolean;
  imageSelect?: boolean;
}

export interface SchemaRuntimeModification {
  description: string;
  removedOption: string;
  updatedHint: string;
  sourceCodeReference: string;
}

export interface SchemaQuestion {
  id: string;
  type: string;
  label: string;
  subtitle: string | null;
  required: boolean;
  multiSelect: boolean;
  options: SchemaOption[];
  visibilityRules: SchemaVisibilityRule[];
  skipLogic: SchemaSkipLogicItem[];
  dependencies: string[];
  dynamicFilterRule?: SchemaDynamicFilterRule;
  mutualExclusivityRules?: SchemaMutualExclusivityRules;
  runtimeModification?: SchemaRuntimeModification;
  validation: SchemaValidation;
  scoringSignals: SchemaScoringSignal[];
  clinicalMappings: SchemaClinicalMapping[];
  uiMetadata: SchemaUIMetadata;
  sourceCodeReference: string;
}

export interface SchemaSection {
  sectionId: string;
  title: string;
  description: string;
  questions: SchemaQuestion[];
}

export interface MasterProtocol {
  schemaVersion: string;
  sourceFile: string;
  extractedBy: string;
  extractionDate: string;
  sections: SchemaSection[];
}

// ─────────────────────────────────────────────────────────────────────────────
// EXPORT
// ─────────────────────────────────────────────────────────────────────────────

export const masterProtocol: MasterProtocol = rawProtocol as MasterProtocol;

export default masterProtocol;
