/**
 * Staging QA auth identities, linked through the real auth path.
 *
 * ── What it creates ─────────────────────────────────────────────────────────
 * Supabase Auth users for the seeded QA doctors, each linked to its Doctor row
 * by `Doctor.supabaseUserId` — the column `requireDoctorContext` actually
 * queries. No parallel auth mechanism, no hardcoded roles: a request resolves
 * exactly as it would in production.
 *
 * It also creates a SECOND clinic with its own doctor. Tenant isolation cannot
 * be proven inside a single clinic — "Doctor A cannot read Doctor B's clinic"
 * needs a Doctor B whose clinic differs. This is the minimum fixture that makes
 * that test meaningful, not extra QA data for its own sake.
 *
 * ── Credentials ─────────────────────────────────────────────────────────────
 * Passwords are generated, never hardcoded, and written to
 * `.env.staging.qa.local` — matched by the `.env.*` rule in .gitignore, so it
 * cannot be committed. They are not printed to stdout.
 *
 * Staging only, guarded three ways. Idempotent: re-running updates the existing
 * users rather than creating duplicates.
 *
 *   CLINIC_SEED_ALLOW=1 npx tsx scripts/db-cli-guard.ts tsx scripts/seed-staging-auth.ts
 */
import { randomBytes } from "node:crypto";
import { writeFileSync } from "node:fs";
import path from "node:path";
import { PrismaClient } from "@prisma/client";
import { createClient } from "@supabase/supabase-js";
import {
  assertSafeDatabaseTarget,
  extractSupabaseRef,
  STAGING_SUPABASE_REF,
} from "../packages/shared/env/databaseTarget";

const prisma = new PrismaClient();
const CRED_FILE = path.resolve(__dirname, "..", ".env.staging.qa.local");

/** Organisation the QA Super Admin belongs to — the hook's role source. */
const ORG_QA = {
  id: "staging-qa-org",
  name: "DrFACT Staging QA Org",
  slug: "drfact-staging-qa",
};

/** Second clinic — exists solely so cross-tenant denial is testable. */
const CLINIC_B = {
  id: "staging-qa-clinic-b",
  name: "DrFACT Pune Test Clinic",
  slug: "drfact-pune-test",
};

interface Identity {
  label: string;
  email: string;
  /** null => attach to the primary seeded clinic */
  clinicId: string | null;
  doctorName: string | null;
}

const IDENTITIES: Identity[] = [
  { label: "DOCTOR_A", email: "dr.test.a@drfact.staging", clinicId: null, doctorName: "Dr Test A" },
  { label: "DOCTOR_B", email: "dr.qa.b@drfact.staging", clinicId: CLINIC_B.id, doctorName: "Dr QA B" },
  { label: "SUPER_ADMIN", email: "admin.qa@drfact.staging", clinicId: null, doctorName: null },
];

function password(): string {
  // Long, random, and URL-safe so it survives a copy/paste into a login form.
  return `Qa-${randomBytes(15).toString("base64url")}`;
}

async function main(): Promise<void> {
  assertSafeDatabaseTarget(process.env, "seed-staging-auth");
  const ref =
    extractSupabaseRef(process.env.DIRECT_URL) ??
    extractSupabaseRef(process.env.DATABASE_URL) ??
    extractSupabaseRef(process.env.NEXT_PUBLIC_SUPABASE_URL);
  if (ref !== STAGING_SUPABASE_REF) {
    throw new Error(`[seed-staging-auth] refusing: resolved ${ref ?? "unknown"}, expected staging.`);
  }
  if (process.env.CLINIC_SEED_ALLOW !== "1") {
    throw new Error("[seed-staging-auth] set CLINIC_SEED_ALLOW=1 to run this seed.");
  }

  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!url || !serviceKey) {
    throw new Error("[seed-staging-auth] NEXT_PUBLIC_SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY are required.");
  }
  const admin = createClient(url, serviceKey, {
    auth: { autoRefreshToken: false, persistSession: false },
  });

  const primaryClinic = await prisma.clinic.findFirst({
    where: { deletedAt: null, NOT: { id: CLINIC_B.id } },
    orderBy: { createdAt: "asc" },
    select: { id: true, name: true },
  });
  if (!primaryClinic) throw new Error("No seeded clinic found — run seed:clinic first.");

  await prisma.clinic.upsert({
    where: { id: CLINIC_B.id },
    update: {},
    create: { ...CLINIC_B, region: "IN", updatedAt: new Date() },
  });

  const lines: string[] = [
    "# Staging QA credentials — generated by scripts/seed-staging-auth.ts",
    "# Ignored by git (.env.* rule). Never commit or paste these anywhere public.",
    `# Supabase project: ${STAGING_SUPABASE_REF}`,
    "",
  ];

  for (const id of IDENTITIES) {
    const pw = password();
    const clinicId = id.clinicId ?? primaryClinic.id;

    // Idempotent: reuse the existing auth user when the email is already taken.
    const { data: list } = await admin.auth.admin.listUsers({ page: 1, perPage: 1000 });
    const existing = list?.users.find((u) => u.email?.toLowerCase() === id.email.toLowerCase());

    let userId: string;
    if (existing) {
      const { data, error } = await admin.auth.admin.updateUserById(existing.id, {
        password: pw,
        email_confirm: true,
      });
      if (error) throw new Error(`${id.label}: ${error.message}`);
      userId = data.user.id;
    } else {
      const { data, error } = await admin.auth.admin.createUser({
        email: id.email,
        password: pw,
        email_confirm: true,
      });
      if (error) throw new Error(`${id.label}: ${error.message}`);
      userId = data.user.id;
    }

    if (id.label === "SUPER_ADMIN") {
      // The hook derives SUPER_ADMIN from OrganizationMember, not from the
      // auth user. Creating the auth identity alone produces a token with no
      // user_role at all, which every admin surface correctly rejects — so the
      // role has to be granted through the same canonical table production
      // uses, never by special-casing the role in application code.
      const org = await prisma.organization.upsert({
        where: { id: ORG_QA.id },
        update: {},
        create: { ...ORG_QA, updatedAt: new Date() },
      });
      const existingMember = await prisma.organizationMember.findFirst({
        where: { supabaseUserId: userId },
        select: { id: true },
      });
      if (existingMember) {
        await prisma.organizationMember.update({
          where: { id: existingMember.id },
          data: { organizationId: org.id, role: "SUPER_ADMIN" },
        });
      } else {
        await prisma.organizationMember.create({
          data: {
            organizationId: org.id,
            supabaseUserId: userId,
            role: "SUPER_ADMIN",
            name: "QA Super Admin",
            email: id.email,
            phone: "+919900019000",
            updatedAt: new Date(),
          },
        });
      }
    }

    if (id.doctorName) {
      // Link through the exact column requireDoctorContext queries.
      const doctor = await prisma.doctor.findFirst({
        where: { clinicId, deletedAt: null, name: id.doctorName },
        select: { id: true },
      });
      if (doctor) {
        await prisma.doctor.update({
          where: { id: doctor.id },
          data: { supabaseUserId: userId, isActive: true },
        });
      } else {
        await prisma.doctor.create({
          data: {
            clinicId,
            name: id.doctorName,
            email: id.email,
            supabaseUserId: userId,
            isActive: true,
            updatedAt: new Date(),
          },
        });
      }
    }

    lines.push(`# ${id.label} — clinic ${clinicId}`);
    lines.push(`${id.label}_EMAIL=${id.email}`);
    lines.push(`${id.label}_PASSWORD=${pw}`);
    lines.push("");
    console.log(`  ${id.label.padEnd(12)} ${id.email.padEnd(30)} authUserId=${userId} clinic=${clinicId}`);
  }

  writeFileSync(CRED_FILE, lines.join("\n"), "utf8");
  console.log(`\n[seed-staging-auth] credentials written to .env.staging.qa.local (git-ignored)`);
  console.log(`[seed-staging-auth] clinic A = ${primaryClinic.id} (${primaryClinic.name})`);
  console.log(`[seed-staging-auth] clinic B = ${CLINIC_B.id} (${CLINIC_B.name})`);
}

main()
  .catch((e) => {
    console.error(e instanceof Error ? e.message : e);
    process.exitCode = 1;
  })
  .finally(() => void prisma.$disconnect());
