import type { DiagnosisKey, TherapyNeed } from '../../types';

// Maps each diagnosis key to its primary therapy needs.
// This is the ONLY place where clinical vocabulary meets therapy vocabulary.
// Contains NO product names.
export const DIAGNOSIS_TO_NEEDS: Record<DiagnosisKey, TherapyNeed[]> = {
  AGA_MALE_123:      ['SHEDDING_ARREST', 'INFLAMMATION_CONTROL', 'DHT_SUPPRESSION', 'METABOLIC_SUPPORT', 'FOLLICLE_STIMULATION'],
  AGA_MALE_45:       ['IMMUNE_MODULATION', 'DHT_SUPPRESSION', 'INFLAMMATION_CONTROL'],
  AGA_FEMALE_123:    ['SHEDDING_ARREST', 'INFLAMMATION_CONTROL', 'DHT_SUPPRESSION', 'METABOLIC_SUPPORT', 'FOLLICLE_STIMULATION'],
  AGA_FEMALE_45:     ['IMMUNE_MODULATION', 'DHT_SUPPRESSION', 'INFLAMMATION_CONTROL'],
  TE_STRESS:         ['SHEDDING_ARREST', 'INFLAMMATION_CONTROL'],
  TE_NUTRITION:      ['SHEDDING_ARREST', 'INFLAMMATION_CONTROL'],
  TE_POSTPREG:       ['LACTATION_SUPPORT', 'SHEDDING_ARREST', 'IMMUNE_MODULATION'],
  TE_DELIVERY:       ['SHEDDING_ARREST', 'IMMUNE_MODULATION'],
  TE_ILLNESS:        ['IMMUNE_MODULATION', 'SHEDDING_ARREST', 'INFLAMMATION_CONTROL'],
  THYROID_HYPO:      ['THYROID_SUPPORT', 'INFLAMMATION_CONTROL', 'SHEDDING_ARREST'],
  THYROID_HYPER:     ['THYROID_SUPPORT', 'SHEDDING_ARREST', 'IMMUNE_MODULATION'],
  PCOS_ONLY:         ['ANDROGENIC_CORRECTION', 'INFLAMMATION_CONTROL', 'SHEDDING_ARREST'],
  PCOS_OBESITY:      ['METABOLIC_SUPPORT', 'ANDROGENIC_CORRECTION', 'INFLAMMATION_CONTROL'],
  PERI_MENOPAUSE:    ['HORMONAL_REBALANCING', 'DHT_SUPPRESSION', 'SHEDDING_ARREST', 'IMMUNE_MODULATION'],
  MENOPAUSE:         ['HORMONAL_REBALANCING', 'DHT_SUPPRESSION', 'SHEDDING_ARREST'],
  POST_MENOPAUSE:    ['HORMONAL_REBALANCING', 'DHT_SUPPRESSION', 'SHEDDING_ARREST', 'IMMUNE_MODULATION'],
  IRON_DEFICIENCY:   ['IRON_REPLETION', 'SHEDDING_ARREST', 'IMMUNE_MODULATION'],
  ALOPECIA_AREATA:   ['IMMUNE_MODULATION', 'METABOLIC_SUPPORT', 'INFLAMMATION_CONTROL', 'FOLLICLE_STIMULATION'],
  PREGNANCY:         ['PREGNANCY_SUPPORT'],
  WEIGHT_LOSS:       ['WEIGHT_LOSS_RECOVERY', 'SHEDDING_ARREST', 'IMMUNE_MODULATION'],
  GUT_ISSUES:        ['GUT_RESTORATION', 'INFLAMMATION_CONTROL', 'IMMUNE_MODULATION', 'SHEDDING_ARREST'],
  SCALP_INFLAM:      ['INFLAMMATION_CONTROL', 'DHT_SUPPRESSION'],
  HAIR_BREAKAGE:     ['SHAFT_REPAIR', 'INFLAMMATION_CONTROL'],
  OXIDATIVE:         ['INFLAMMATION_CONTROL', 'ANTIOXIDANT_SUPPORT', 'IMMUNE_MODULATION'],
  NIGHT_SHIFT:       ['CIRCADIAN_RESET', 'SHEDDING_ARREST', 'INFLAMMATION_CONTROL'],
  FREQUENT_FLYING:   ['CIRCADIAN_RESET', 'SHEDDING_ARREST', 'INFLAMMATION_CONTROL'],
  DIABETES:          ['METABOLIC_SUPPORT', 'INFLAMMATION_CONTROL', 'IMMUNE_MODULATION'],
  CHRONIC_MEDICAL:   ['IMMUNE_MODULATION', 'INFLAMMATION_CONTROL'],
  TTM:               ['NEUROLOGICAL_OCD_SUPPORT', 'SHEDDING_ARREST', 'INFLAMMATION_CONTROL'],
  ENDOMETRIOSIS:     ['HORMONAL_REBALANCING', 'INFLAMMATION_CONTROL', 'IMMUNE_MODULATION'],
  EARLY_GREY:        ['MELANOCYTE_PROTECTION', 'ANTIOXIDANT_SUPPORT', 'IMMUNE_MODULATION'],
  MOUTH_ULCERS:      ['INFLAMMATION_CONTROL', 'IMMUNE_MODULATION', 'ANTIOXIDANT_SUPPORT'],
  MULTI:             ['INFLAMMATION_CONTROL', 'SHEDDING_ARREST', 'GUT_RESTORATION', 'DHT_SUPPRESSION'],
  REGROW_ONLY:       ['FOLLICLE_STIMULATION', 'INFLAMMATION_CONTROL', 'METABOLIC_SUPPORT'],
};

// Additive needs surfaced by secondary conditions.
export const SECONDARY_NEEDS: Partial<Record<DiagnosisKey, TherapyNeed[]>> = {
  IRON_DEFICIENCY:  ['IRON_REPLETION'],
  GUT_ISSUES:       ['GUT_RESTORATION'],
  OXIDATIVE:        ['ANTIOXIDANT_SUPPORT'],
  SCALP_INFLAM:     ['INFLAMMATION_CONTROL'],
  HAIR_BREAKAGE:    ['SHAFT_REPAIR'],
  DIABETES:         ['METABOLIC_SUPPORT'],
  THYROID_HYPO:     ['THYROID_SUPPORT'],
  ALOPECIA_AREATA:  ['IMMUNE_MODULATION'],
};
